### PR TITLE
Initial structure of Node rebuild

### PR DESCRIPTION
**Pull request by DanTheManGude**
Login page
API calls for authorizing users against mocked whitelist
Stubbed routes for main navigation bar, music, and 404

Backend powered by Express.js
Frontend created by Create React App
Routing done by React Router
Google login through Firebase

### CODE REVIEW

**Comment by saf6260** [comment]
-> I still feel firebase is not a valuable solution to login for this system and should be removed before this is merged in to the system
-> Glad to see redux wasn't implemented
-> The functionality of everything else looks good to me
-> Jeez that's a lot of commits

**Comment by DanTheManGude** [comment]
Redux is implemented but we can remove it.

**Comment by wylaris** [comment]
I'm going to open and approve a PR from master into Dev so we can reduce the changes in this PR to only be the React code for clarity's sake.

**Comment by wylaris** [comment]
npm start failed.

**Comment by wylaris** [comment]
Warnings: npm WARN PepBandWebsite@0.0.1 No repository field.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

**Comment by wylaris** [comment]
Consider adding ``    * sudo apt install nodejs (If not installed)`,  `    * wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash (If not installed)
`, and `    * sudo apt install npm
` for verbose readme

**Pull request merged**
